// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: protos/robot_config.proto's 9 wire-addressable groups
// (protocol v6 spec §7.3)
#pragma once

#include <cmath>
#include <cstddef>
#include <cstdint>

#include "config/robot.h"

namespace Config::WireV6 {

enum class FieldType : uint8_t { kFloat, kI32, kU32 };

// ConfigFieldEntry -- one row of protocol v6's 80-row config field
// table (spec §7.3): name ("<group>.<field>", lowercase), byte offset
// into Config::Robot, storage type, scale, and the declared [min, max]
// bound. `scale` is always 1.0 here -- config values are plain decimal
// on the wire (spec §7.2), never wire-scaled the way telemetry columns
// are -- kept for shape parity with the spec's own "name, offset,
// type, scale, min, max" table description (§7.3). A field with no
// declared bound reads [-INFINITY, +INFINITY], so an unconditional
// `< min` / `> max` compare never rejects it. Generated from
// protos/robot_config.proto's 9 wire-addressable groups -- the SAME
// field-descriptor walk that already generates Config::Robot's own
// C++ members (132-002), so a field can never drift between "what
// Config::Robot stores" and "what this table thinks it stores".
// `SET`/`GET` lookup against this table is ticket 002's job, not this
// one.
struct ConfigFieldEntry {
    const char* name;
    size_t offset;
    FieldType type;
    float scale;
    float min;
    float max;
};

constexpr ConfigFieldEntry kConfigFieldTable[80] = {
    { "geometry.trackwidth", offsetof(Config::Robot, geometry) + offsetof(msg::Geometry, trackwidth), FieldType::kFloat, 1.0f, 1.0f, INFINITY },
    { "geometry.rotational_slip", offsetof(Config::Robot, geometry) + offsetof(msg::Geometry, rotational_slip), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "geometry.rotation_gain_pos", offsetof(Config::Robot, geometry) + offsetof(msg::Geometry, rotation_gain_pos), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "geometry.rotation_offset", offsetof(Config::Robot, geometry) + offsetof(msg::Geometry, rotation_offset), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "geometry.rotation_gain_neg", offsetof(Config::Robot, geometry) + offsetof(msg::Geometry, rotation_gain_neg), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "geometry.rotation_offset_neg", offsetof(Config::Robot, geometry) + offsetof(msg::Geometry, rotation_offset_neg), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "motors.left_port", offsetof(Config::Robot, motors) + offsetof(msg::Motors, left_port), FieldType::kU32, 1.0f, 1.0f, 4.0f },
    { "motors.right_port", offsetof(Config::Robot, motors) + offsetof(msg::Motors, right_port), FieldType::kU32, 1.0f, 1.0f, 4.0f },
    { "motors.travel_calib_left", offsetof(Config::Robot, motors) + offsetof(msg::Motors, travel_calib_left), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "motors.travel_calib_right", offsetof(Config::Robot, motors) + offsetof(msg::Motors, travel_calib_right), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "motors.fwd_sign_left", offsetof(Config::Robot, motors) + offsetof(msg::Motors, fwd_sign_left), FieldType::kI32, 1.0f, -1.0f, 1.0f },
    { "motors.fwd_sign_right", offsetof(Config::Robot, motors) + offsetof(msg::Motors, fwd_sign_right), FieldType::kI32, 1.0f, -1.0f, 1.0f },
    { "motors.output_deadband", offsetof(Config::Robot, motors) + offsetof(msg::Motors, output_deadband), FieldType::kFloat, 1.0f, -1.0f, 1.0f },
    { "motors.reversal_dwell", offsetof(Config::Robot, motors) + offsetof(msg::Motors, reversal_dwell), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "motors.vel_kp", offsetof(Config::Robot, motors) + offsetof(msg::Motors, vel_kp), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "motors.vel_ki", offsetof(Config::Robot, motors) + offsetof(msg::Motors, vel_ki), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "motors.vel_kff", offsetof(Config::Robot, motors) + offsetof(msg::Motors, vel_kff), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "motors.vel_i_max", offsetof(Config::Robot, motors) + offsetof(msg::Motors, vel_i_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "motors.vel_kaw", offsetof(Config::Robot, motors) + offsetof(msg::Motors, vel_kaw), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "motors.vel_filt_alpha", offsetof(Config::Robot, motors) + offsetof(msg::Motors, vel_filt_alpha), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "drive.duty_per_speed_left", offsetof(Config::Robot, drive) + offsetof(msg::Drive, duty_per_speed_left), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "drive.duty_per_speed_right", offsetof(Config::Robot, drive) + offsetof(msg::Drive, duty_per_speed_right), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "drive.crawl_pulse", offsetof(Config::Robot, drive) + offsetof(msg::Drive, crawl_pulse), FieldType::kFloat, 1.0f, -1.0f, 1.0f },
    { "drive.wheel_gain_left_accel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_gain_left_accel), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "drive.wheel_intercept_left_accel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_intercept_left_accel), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "drive.wheel_gain_left_decel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_gain_left_decel), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "drive.wheel_intercept_left_decel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_intercept_left_decel), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "drive.wheel_gain_right_accel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_gain_right_accel), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "drive.wheel_intercept_right_accel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_intercept_right_accel), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "drive.wheel_gain_right_decel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_gain_right_decel), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "drive.wheel_intercept_right_decel", offsetof(Config::Robot, drive) + offsetof(msg::Drive, wheel_intercept_right_decel), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "wheel_control.v_min", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, v_min), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.bias_max", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, bias_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.tau_adapt", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, tau_adapt), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.a_steady", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, a_steady), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.deficit_threshold", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, deficit_threshold), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.deficit_window", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, deficit_window), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.pid_kp", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, pid_kp), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.pid_ki", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, pid_ki), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.pid_i_max", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, pid_i_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.pid_kaff", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, pid_kaff), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.pid_max", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, pid_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.pos_err_max", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, pos_err_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.stall_speed", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, stall_speed), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.stall_demand", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, stall_demand), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "wheel_control.stall_window", offsetof(Config::Robot, wheelControl) + offsetof(msg::WheelControl, stall_window), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.v_max", offsetof(Config::Robot, planner) + offsetof(msg::Planner, v_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.omega_max", offsetof(Config::Robot, planner) + offsetof(msg::Planner, omega_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.control_period", offsetof(Config::Robot, planner) + offsetof(msg::Planner, control_period), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.actuation_delay", offsetof(Config::Robot, planner) + offsetof(msg::Planner, actuation_delay), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.settle_rest_velocity", offsetof(Config::Robot, planner) + offsetof(msg::Planner, settle_rest_velocity), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.settle_rest_omega", offsetof(Config::Robot, planner) + offsetof(msg::Planner, settle_rest_omega), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.settle_epsilon_linear", offsetof(Config::Robot, planner) + offsetof(msg::Planner, settle_epsilon_linear), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.settle_epsilon_angular", offsetof(Config::Robot, planner) + offsetof(msg::Planner, settle_epsilon_angular), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.heading_hold_gain", offsetof(Config::Robot, planner) + offsetof(msg::Planner, heading_hold_gain), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.decel_plan_fraction", offsetof(Config::Robot, planner) + offsetof(msg::Planner, decel_plan_fraction), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.align_tol", offsetof(Config::Robot, planner) + offsetof(msg::Planner, align_tol), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner.align_max_nudges", offsetof(Config::Robot, planner) + offsetof(msg::Planner, align_max_nudges), FieldType::kI32, 1.0f, 0.0f, INFINITY },
    { "planner_shaper.a_max", offsetof(Config::Robot, plannerShaper) + offsetof(msg::PlannerShaper, a_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner_shaper.a_decel", offsetof(Config::Robot, plannerShaper) + offsetof(msg::PlannerShaper, a_decel), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner_shaper.alpha_max", offsetof(Config::Robot, plannerShaper) + offsetof(msg::PlannerShaper, alpha_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner_shaper.alpha_decel", offsetof(Config::Robot, plannerShaper) + offsetof(msg::PlannerShaper, alpha_decel), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner_shaper.jerk_max", offsetof(Config::Robot, plannerShaper) + offsetof(msg::PlannerShaper, jerk_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "planner_shaper.yaw_jerk_max", offsetof(Config::Robot, plannerShaper) + offsetof(msg::PlannerShaper, yaw_jerk_max), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.speed", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, speed), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.max_wheel_step", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, max_wheel_step), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.behind_angle", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, behind_angle), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.turn_first_angle", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, turn_first_angle), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.approach_radius", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, approach_radius), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.approach_speed", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, approach_speed), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.default_arrival_tolerance", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, default_arrival_tolerance), FieldType::kFloat, 1.0f, 0.0f, INFINITY },
    { "navigator.yaw_sign", offsetof(Config::Robot, navigator) + offsetof(msg::Navigator, yaw_sign), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "otos.offset_x", offsetof(Config::Robot, otos) + offsetof(msg::Otos, offset_x), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "otos.offset_y", offsetof(Config::Robot, otos) + offsetof(msg::Otos, offset_y), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "otos.offset_yaw", offsetof(Config::Robot, otos) + offsetof(msg::Otos, offset_yaw), FieldType::kFloat, 1.0f, -INFINITY, INFINITY },
    { "otos.linear_scale", offsetof(Config::Robot, otos) + offsetof(msg::Otos, linear_scale), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "otos.angular_scale", offsetof(Config::Robot, otos) + offsetof(msg::Otos, angular_scale), FieldType::kFloat, 1.0f, 0.0001f, INFINITY },
    { "estimator.weight_heading_otos", offsetof(Config::Robot, estimator) + offsetof(msg::Estimator, weight_heading_otos), FieldType::kFloat, 1.0f, 0.0f, 1.0f },
    { "estimator.weight_omega_otos", offsetof(Config::Robot, estimator) + offsetof(msg::Estimator, weight_omega_otos), FieldType::kFloat, 1.0f, 0.0f, 1.0f },
    { "estimator.staleness", offsetof(Config::Robot, estimator) + offsetof(msg::Estimator, staleness), FieldType::kU32, 1.0f, -INFINITY, INFINITY },
};
constexpr uint16_t kConfigFieldCount = 80;

}  // namespace Config::WireV6
