// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: scripts/wire_v6_tables.py (protocol v6 spec §6.3/§6.4)
#pragma once

#include <cstdint>

namespace msg::wire_v6 {

// kPoseColumns/kFullColumns -- protocol v6's telemetry column NAME
// tables (spec §6.3 POSE / §6.4 FULL), in wire column order. `thdr:`
// emits these names once per subscription change; `t:` emits the
// matching values every frame (spec §6.2). Assembling those values
// from RobotState is ticket 004's job, not this one -- this header
// only fixes the column NAMES and their ORDER, generated so the
// firmware table and the host mirror below can never independently
// drift on either.
constexpr const char* kPoseColumns[9] = {
    "seq", "now", "flags", "x", "y", "h", "ox", "oy", "oh",
};
constexpr uint8_t kPoseColumnCount = 9;

constexpr const char* kFullColumns[35] = {
    "seq", "now", "flags", "x", "y", "h",
    "ox", "oy", "oh", "mode", "elp", "elv",
    "ela", "ele", "erp", "erv", "era", "ere",
    "ovx", "ovy", "ow", "oa", "tvx", "tvy",
    "tw", "l1", "l2", "l3", "l4", "cr",
    "cg", "cb", "cc", "cyb", "cyp",
};
constexpr uint8_t kFullColumnCount = 35;

}  // namespace msg::wire_v6
