// AUTO-GENERATED — do not edit by hand.
// Regenerated by scripts/gen_messages.py before each firmware build.
// Source: scripts/wire_v6_tables.py (protocol v6 spec §3)
#pragma once

#include <cstdint>

namespace msg::wire_v6 {

// VerbEntry -- one row of protocol v6's flat verb table (sprint 137
// ticket 001, Design Rationale Decision 2): the wire verb text, its
// direction (host->robot command vs. robot->host reply), and the spec's
// own Fields column verbatim. Generated from scripts/wire_v6_tables.py --
// the ONE source this table and the host wire_v6_tables_generated.py
// mirror both come from. Dispatch (looking a parsed verb up in this
// table by name/case/arity) is a later ticket's job (002/004/006/008),
// not this one -- see this ticket's own scope note.
struct VerbEntry {
    const char* verb;
    bool isCommand;      // true: host -> robot command; false: robot -> host reply
    const char* fields;  // spec's own Fields column, verbatim; "-" if none
    const char* section; // spec section reference, e.g. "5.1"
};

constexpr VerbEntry kVerbTable[30] = {
    { "HELLO", true, "-", "4" },
    { "PING", true, "-", "4" },
    { "ID", true, "-", "4" },
    { "VER", true, "-", "4" },
    { "STATUS", true, "-", "4" },
    { "HELP", true, "-", "4" },
    { "GET", true, "[name]", "7" },
    { "SET", true, "name:value[:id]", "7" },
    { "TLM", true, "mode", "6" },
    { "MOVE", true, "kind:a:b:c:stop:limit:timeout:id", "5.1" },
    { "WHEELS", true, "left:right:duration[:id]", "5.2" },
    { "GOTO", true, "x:y:frame:speed:arrive:timeout:id", "5.3" },
    { "STOP", true, "id", "5.4" },
    { "ESTOP", true, "-", "5.4" },
    { "SEED", true, "x:y:h[:id]", "5.5" },
    { "CAL", true, "[samples][:id]", "5.6" },
    { "device", false, "NEZHA2:robot:<name>:<serial>", "4" },
    { "ready", false, "-", "4" },
    { "pong", false, "<now>", "4" },
    { "id", false, "<drivetrain>:<profile>:<version>", "4" },
    { "ver", false, "<version>", "4" },
    { "status", false, "k=v:k=v:...", "4" },
    { "help", false, "<verb> <verb> ...", "4" },
    { "get", false, "name:value", "7" },
    { "ok", false, "id", "8" },
    { "err", false, "id:code", "8" },
    { "done", false, "id:reason", "8" },
    { "thdr", false, "col:col:...", "6.2" },
    { "t", false, "val:val:...", "6.2" },
    { "dbg", false, "<free text>", "4" },
};
constexpr uint8_t kVerbCount = 30;

}  // namespace msg::wire_v6
