"""wire_v6_tables_generated.py -- GENERATED protocol v6 flat wire tables
(sprint 137 ticket 001).

AUTO-GENERATED by scripts/gen_messages.py -- do not edit by hand.
Sources: scripts/wire_v6_tables.py (verb table, spec §3; telemetry column
tables, spec §6.3/§6.4) and protos/robot_config.proto's 9 wire-addressable
groups (config field table, spec §7.3).

The firmware tables (src/firm/messages/wire_v6_verbs.h,
src/firm/messages/wire_v6_telemetry.h,
src/firm/config/wire_v6_config_fields.h) and this host module are
generated from the SAME declarations -- sprint 137 sprint.md Design
Rationale Decision 2 ("one declaration, two generated outputs"), the
property that makes the v5-era `pid.kff -> kaff` drift class structurally
impossible: there is no second hand-maintained copy of a verb, column, or
field name to drift from.

This ticket (137-001) lands the generator and its generated output only --
it does not wire GET/SET/TLM/dispatch against these tables (that is
tickets 002/004/008).

Regenerate: python3 src/scripts/gen_messages.py
"""

from __future__ import annotations

from typing import NamedTuple


class VerbEntry(NamedTuple):
    verb: str
    is_command: bool  # True: host -> robot command; False: robot -> host reply
    fields: str        # spec's own Fields column, verbatim; "-" if none
    section: str        # spec section reference, e.g. "5.1"


class ConfigFieldEntry(NamedTuple):
    name: str   # "<group>.<field>", lowercase (spec §7.3)
    type: str    # "float" | "i32" | "u32"
    scale: float  # always 1.0 -- config values are plain decimal (spec §7.2)
    min: float
    max: float

VERBS: tuple[VerbEntry, ...] = (
    VerbEntry("HELLO", True, "-", "4"),
    VerbEntry("PING", True, "-", "4"),
    VerbEntry("ID", True, "-", "4"),
    VerbEntry("VER", True, "-", "4"),
    VerbEntry("STATUS", True, "-", "4"),
    VerbEntry("HELP", True, "-", "4"),
    VerbEntry("GET", True, "[name]", "7"),
    VerbEntry("SET", True, "name:value[:id]", "7"),
    VerbEntry("TLM", True, "mode", "6"),
    VerbEntry("MOVE", True, "kind:a:b:c:stop:limit:timeout:id", "5.1"),
    VerbEntry("WHEELS", True, "left:right:duration[:id]", "5.2"),
    VerbEntry("GOTO", True, "x:y:frame:speed:arrive:timeout:id", "5.3"),
    VerbEntry("STOP", True, "id", "5.4"),
    VerbEntry("ESTOP", True, "-", "5.4"),
    VerbEntry("SEED", True, "x:y:h[:id]", "5.5"),
    VerbEntry("CAL", True, "[samples][:id]", "5.6"),
    VerbEntry("device", False, "NEZHA2:robot:<name>:<serial>", "4"),
    VerbEntry("ready", False, "-", "4"),
    VerbEntry("pong", False, "<now>", "4"),
    VerbEntry("id", False, "<drivetrain>:<profile>:<version>", "4"),
    VerbEntry("ver", False, "<version>", "4"),
    VerbEntry("status", False, "k=v:k=v:...", "4"),
    VerbEntry("help", False, "<verb> <verb> ...", "4"),
    VerbEntry("get", False, "name:value", "7"),
    VerbEntry("ok", False, "id", "8"),
    VerbEntry("err", False, "id:code", "8"),
    VerbEntry("done", False, "id:reason", "8"),
    VerbEntry("thdr", False, "col:col:...", "6.2"),
    VerbEntry("t", False, "val:val:...", "6.2"),
    VerbEntry("dbg", False, "<free text>", "4"),
)
VERB_BY_NAME: dict[str, VerbEntry] = {v.verb: v for v in VERBS}
COMMANDS: tuple[VerbEntry, ...] = tuple(v for v in VERBS if v.is_command)
REPLIES: tuple[VerbEntry, ...] = tuple(v for v in VERBS if not v.is_command)

POSE_COLUMNS: tuple[str, ...] = (
    "seq", "now", "flags", "x", "y", "h", "ox", "oy", "oh",
)
FULL_COLUMNS: tuple[str, ...] = (
    "seq", "now", "flags", "x", "y", "h",
    "ox", "oy", "oh", "mode", "elp", "elv",
    "ela", "ele", "erp", "erv", "era", "ere",
    "ovx", "ovy", "ow", "oa", "tvx", "tvy",
    "tw", "l1", "l2", "l3", "l4", "cr",
    "cg", "cb", "cc", "cyb", "cyp",
)

CONFIG_FIELDS: tuple[ConfigFieldEntry, ...] = (
    ConfigFieldEntry("geometry.trackwidth", "float", 1.0, 1.0, float("inf")),
    ConfigFieldEntry("geometry.rotational_slip", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("geometry.rotation_gain_pos", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("geometry.rotation_offset", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("geometry.rotation_gain_neg", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("geometry.rotation_offset_neg", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("motors.left_port", "u32", 1.0, 1.0, 4.0),
    ConfigFieldEntry("motors.right_port", "u32", 1.0, 1.0, 4.0),
    ConfigFieldEntry("motors.travel_calib_left", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("motors.travel_calib_right", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("motors.fwd_sign_left", "i32", 1.0, -1.0, 1.0),
    ConfigFieldEntry("motors.fwd_sign_right", "i32", 1.0, -1.0, 1.0),
    ConfigFieldEntry("motors.output_deadband", "float", 1.0, -1.0, 1.0),
    ConfigFieldEntry("motors.reversal_dwell", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("motors.vel_kp", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("motors.vel_ki", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("motors.vel_kff", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("motors.vel_i_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("motors.vel_kaw", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("motors.vel_filt_alpha", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("drive.duty_per_speed_left", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("drive.duty_per_speed_right", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("drive.crawl_pulse", "float", 1.0, -1.0, 1.0),
    ConfigFieldEntry("drive.wheel_gain_left_accel", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("drive.wheel_intercept_left_accel", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("drive.wheel_gain_left_decel", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("drive.wheel_intercept_left_decel", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("drive.wheel_gain_right_accel", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("drive.wheel_intercept_right_accel", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("drive.wheel_gain_right_decel", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("drive.wheel_intercept_right_decel", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("wheel_control.v_min", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.bias_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.tau_adapt", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.a_steady", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.deficit_threshold", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.deficit_window", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.pid_kp", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.pid_ki", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.pid_i_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.pid_kaff", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.pid_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.pos_err_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.stall_speed", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.stall_demand", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("wheel_control.stall_window", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.v_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.omega_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.control_period", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.actuation_delay", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.settle_rest_velocity", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.settle_rest_omega", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.settle_epsilon_linear", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.settle_epsilon_angular", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.heading_hold_gain", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.decel_plan_fraction", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.align_tol", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner.align_max_nudges", "i32", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner_shaper.a_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner_shaper.a_decel", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner_shaper.alpha_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner_shaper.alpha_decel", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner_shaper.jerk_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("planner_shaper.yaw_jerk_max", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.speed", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.max_wheel_step", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.behind_angle", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.turn_first_angle", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.approach_radius", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.approach_speed", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.default_arrival_tolerance", "float", 1.0, 0.0, float("inf")),
    ConfigFieldEntry("navigator.yaw_sign", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("otos.offset_x", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("otos.offset_y", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("otos.offset_yaw", "float", 1.0, float("-inf"), float("inf")),
    ConfigFieldEntry("otos.linear_scale", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("otos.angular_scale", "float", 1.0, 0.0001, float("inf")),
    ConfigFieldEntry("estimator.weight_heading_otos", "float", 1.0, 0.0, 1.0),
    ConfigFieldEntry("estimator.weight_omega_otos", "float", 1.0, 0.0, 1.0),
    ConfigFieldEntry("estimator.staleness", "u32", 1.0, float("-inf"), float("inf")),
)
CONFIG_FIELD_BY_NAME: dict[str, ConfigFieldEntry] = {f.name: f for f in CONFIG_FIELDS}
